ゲームオーバーの検知のみ。メッセージなどは表示してません
2024-01-12-teamdev-Blue/tetris pull request #32
Opened 2024-01-27 04:45 UTC by fununnn

ゲームオーバーの検知のみ。メッセージなどは表示してません

2024-01-27 06:30 UTC, v8yte requested changes

2024-01-27 06:30 UTC, v8yte commented on js/model/gameModel.js
> +        //ゲームオーバーなら落とさない
ゲームオーバーの場合、落とさないではなく処理を止めたいです。

2024-01-27 06:30 UTC, v8yte commented on js/view/gameView.js
> +        if(!GameModel.gameOverFlag){
描画を止めたいのではなく処理を止めたいです。

2024-01-27 06:34 UTC, v8yte commented
やりたいことが少し違いました。このプログラムだとブロックの落下や描画を止めて外見上は止まっていますが、裏ではしっかりプログラムが動いています。
処理自体を止めたいです。今回のテトリスプログラムではsetIntervalという関数を使って一定時間ごとに処理を行っています。そこでフラグを受け取って止めるようにしましょう。
あと.DS_Storeがpushされているのでそれも上げないようにしてください。

2024-01-27 11:34 UTC, fununnn commented
なるほど、明日確認します。

2024-01-27 23:39 UTC, fununnn commented on js/model/gameModel.js
> +        //ゲームオーバーなら落とさない
一旦消します。

2024-01-27 23:39 UTC, fununnn commented on js/view/gameView.js
> +        if(!GameModel.gameOverFlag){
一旦消します。

2024-01-28 00:37 UTC, fununnn commented
修正してみました。。

2024-01-28 01:02 UTC, v8yte requested changes
意図した動きになっていないと思います。難しければ別のタスク割り振りますができそうですか？

2024-01-28 01:02 UTC, ngin8-beta commented on .gitignore
>  .vscode/
.gitignore自体もpushやめたいですね

2024-01-28 01:02 UTC, ngin8-beta commented on js/.DS_Store
git rmしました？

2024-01-28 01:02 UTC, v8yte commented on js/controller/gameController.js
> +        if(this.model.checkGameOver()){
ここに書くとインターバルの外になってしまうので多分チェック走らないですね。

2024-01-28 01:10 UTC, fununnn commented on .gitignore
>  .vscode/
修正しました

2024-01-28 01:10 UTC, fununnn commented on js/.DS_Store
修正しました

2024-01-28 01:11 UTC, fununnn commented
うむむ、お願いしてもいいですか？ちょっと他のできそうなやつを探してみます

2024-01-28 05:09 UTC, v8yte commented
@fununnn レビューお願いします。

2024-01-28 05:10 UTC, v8yte commented
@fununnn レビューお願いします。

2024-01-28 06:51 UTC, v8yte approved these changes

2024-01-28 06:51 UTC, merged