スコア計算の実装
2024-01-12-teamdev-Blue/tetris pull request #37
Opened 2024-01-28 09:15 UTC by fununnn

#25 スコアはコンソール上に表示されています。

スコア画面に実装する改修が必要です。

2024-01-28 11:34 UTC, v8yte requested changes
処理としてはOKです。
現在、 develop branchとの間でconflictが発生していますので調べて、できれば解消してみてください。

2024-01-28 11:34 UTC, v8yte commented on js/model/gameModel.js
> +    const linesScore = [0,100,300,500,800];
インデントは揃えましょう。

2024-01-28 12:02 UTC, fununnn commented on js/model/gameModel.js
> +    const linesScore = [0,100,300,500,800];
気づかなかったです、修正しましたありがとうございます。

2024-01-28 12:03 UTC, fununnn commented
コンフリクト箇所について、マージの上、両方を承認し解消しました。いい勉強になりました。。

2024-01-28 13:38 UTC, v8yte requested changes
このように2つをとりいれてマージすると処理の整合性が取れなくなることがあります。
コードを読んで適切に取捨選択する必要があります。

2024-01-28 13:38 UTC, v8yte commented on js/model/gameModel.js
>              this.currentTetromino = this.createNewTetromino();
この一行が不要になると思います。
このあとの`const tetromino = this.createNewTetromino();`にてもう一度this.createNewTetromino()が呼ばれています。
つまり一度の処理で二回新しいテトロミノを取ってきています。
また、currentTetrominoにはgame overではないときのみ代入したいので、ここで代入してはいけません。

2024-01-28 22:35 UTC, fununnn commented on js/model/gameModel.js
>              this.currentTetromino = this.createNewTetromino();
なるほど、、今後気をつけます。今日家に帰ったら修正します

2024-01-29 21:16 UTC, fununnn commented on js/model/gameModel.js
>              this.currentTetromino = this.createNewTetromino();
修正しましたので、レビューをお願いします。コンフリクトしていたdrop()のうち、二重になっていたconst tetromino = this.createNewTetromino();を削除しました。

2024-01-29 21:53 UTC, fununnn commented on js/model/gameModel.js
>              this.currentTetromino = this.createNewTetromino();
テストを承認後、またコンフリクトしたのかと思ってGITPULLの上、マージしましたがSome checks were not successfulのまますすみません。

テストで失敗？しているようですがごめんなさいこのまま出勤します

2024-02-02 12:45 UTC, closed without merging