Calc2
2024-01-12-teamdev-Blue/tetris pull request #43
Opened 2024-02-02 13:21 UTC by fununnn

#25

2024-02-02 13:30 UTC, fununnn commented
テストで弾かれていた原因を修正しました。

2024-02-02 13:42 UTC, v8yte requested changes

2024-02-02 13:42 UTC, v8yte commented on js/model/gameModel.js
> +            this.currentTetromino = this.createNewTetromino();
checkGameOverをする前にthis.currentTetrominoに入れてはいけません。
ゲームオーバーではないか確認してからthis.currentTetrominoに入れて描画しています。
ここで代入するとゲームオーバーしているときも描画され、ゲームオーバー時にブロックが重なるように描画されてしまいます。

2024-02-03 01:41 UTC, fununnn commented on js/model/gameModel.js
> +            this.currentTetromino = this.createNewTetromino();
修正しました。指摘にはありませんでしたがthis.checklines();はif文で実行される手順でカバーされていると判断し消しました。
あとちょっとだけ見やすくしました。

2024-02-03 11:22 UTC, v8yte requested changes

2024-02-03 11:22 UTC, v8yte commented on js/model/gameModel.js
>              this.checkLines();
114行目のthis.checkLinea()いらないと思います。
110行目のconst clearedLines = this.checkLines();で行っているので無駄な処理です。

2024-02-03 11:32 UTC, fununnn commented on js/model/gameModel.js
>              this.checkLines();
不要なコードを削除しました。ありがとうございます。

2024-02-03 13:11 UTC, v8yte requested changes
OK

2024-02-03 13:11 UTC, v8yte approved these changes

2024-02-03 13:12 UTC, merged