出てくるミノが7種1巡ではなくなってしまいました。どこをどう直したらよいかわからないので一度見ていただけますでしょうか
2024-01-12-teamdev-Blue/tetris pull request #46
Opened 2024-02-03 15:58 UTC by udonsobaudon

行き詰まってしまいました。お助けください。

2024-02-03 16:29 UTC, udonsobaudon commented
.vscodeは消しておきます。

2024-02-03 16:40 UTC, v8yte requested changes

2024-02-03 16:40 UTC, v8yte commented on js/model/gameModel.js
> +
ここら辺の処理の流れがおかしいです。
もともと下記のような感じになっていたと思います。
```
            //ゲームオーバー判定
            const tetromino = this.createNewTetromino();
            if (this.checkGameOver(tetromino)) {
                this.isGameOver = true;
            }else{
                this.currentTetromino = tetromino;
            }
```
これはtetrominoにいったん次に落とす予定のテトロミノを入れてthis.checkGameOver(tetromino)でゲームーオーバーか判定して、ゲームオーバーでなかった場合にのみthis.currentTetrominoに入れています。
そしてthis.currentTetrominoをrenderする(描画する)処理になっています。

しかしここにthis.updateTetriminos();をいれることで一連の処理にthis.createNewTetromino();が2回処理されていることになります。

2024-02-04 01:34 UTC, v8yte approved these changes

2024-02-04 01:34 UTC, merged