７種類のテトリミノを作成してみました
2024-01-12-teamdev-Blue/tetris pull request #9
Opened 2024-01-21 13:05 UTC by udonsobaudon

gameModel.jsを編集し、７種類のテトリミノを作成してみました。一応エラーは出なかったと思いますが...

2024-01-21 14:52 UTC, v8yte commented
#6

2024-01-21 15:49 UTC, v8yte requested changes
おしい！2点修正点があります。

2024-01-21 15:49 UTC, v8yte commented on .vscode/launch.json
> +{
.vscodeディレクトリは個人的な設定ファイルが入っています。みんなで共有するものではないのでpushしないようにしましょう。
.gitignore/git rm --cachedなどで検索すると追跡させない方法が出てきます。

2024-01-21 15:49 UTC, v8yte commented on js/model/gameModel.js
> +        const block = blocks[Math.floor(Math.random()*blocks.length)];
ランダムのアルゴリズムを再考してみましょう。
1つのバッグに7つのテトリミノがランダムな順番で入っているイメージです。つまりどのパターンのテトリミノも7回に1回は必ず出現するようにしたいです。

2024-01-23 02:36 UTC, v8yte commented
@udonsobaudon 
これ閉じないでこのプルリクの中で対応していきましょう。流れがわからなくなるので。
レビューに対応するときの流れについてまとめてある記事がありますので目を通しておいてください。[https://tonari-it.com/github-request-changes-fix/]

2024-01-26 12:48 UTC, udonsobaudon commented
.vscodeの追跡をやめました

2024-01-26 13:30 UTC, closed without merging